Gsup\ForumBundle\Document\Category:
    type: document
    fields:
        id:
            id: true
        name:
            type: string
        slug:
            type: string
            gedmo:
                slug:
                    separator: -
                    style: default
                    fields:
                        - name
        stats_posts:
            type: int
    referenceMany:
        ancestor:
            targetDocument: Category