Gsup\ForumBundle\Document\Post:
    type: document
    repositoryClass: Gsup\ForumBundle\Repository\PostRepository
    fields:
        id:
            id: true
        title:
            type: string
        slug:
            type: string
            index: true
            unique: true
            gedmo:
                slug:
                    separator: -
                    style: default
                    fields:
                        - title
        content:
            type: string
        rate:
            type: int
        tags:
            type: hash
        stats_comment:
            type: int
        stats_view:
            type: int
        stats_answer:
            type: int
        is_authorized_user:
            type: boolean
        is_request_open:
            type: boolean
        is_request_close:
            type: boolean
        is_resolved:
            type: boolean
        is_closed:
            type: boolean
        is_active:
            type: boolean
        updated_at:
            type: timestamp
        updated_any_at:
            type: timestamp
        created_at:
            type: timestamp
    embedMany:
        reply:
            targetDocument: Reply
        comment:
            targetDocument: Comment
    referenceOne:
        category:
            targetDocument: Category
        user:
            targetDocument: User
        userLastEdit:
            targetDocument: User
        userLastUpdatedAny:
            targetDocument: User