Gsup\ForumBundle\Document\Reply:
    type: embeddedDocument
    fields:
        id:
            id: true
        hash_id:
            type: string
            index: true
            unique: true
        content:
            type: string
        rate:
            type: int
        stats_comment:
            type: int
        is_authorized_user:
            type: boolean
        is_active:
            type: boolean
        updated_at:
            type: timestamp
        updated_any_at:
            type: timestamp
        created_at:
            type: timestamp
    embedMany:
        comment:
            targetDocument: Comment
    referenceOne:
        user:
            targetDocument: User
        userLastEdit:
            targetDocument: User