Gsup\ForumBundle\Document\Tag:
    type: document
    fields:
        id:
            id: true
        name:
            type: string
        slug:
            type: string
            gedmo:
                slug:
                    separator: -
                    style: default
                    fields:
                        - name
        stats_total:
            type: int
