<?php

namespace Gsup\ForumBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends DocumentRepository
{
    /**
     * Find active post document.
     *
     * @param $slug
     * @return mixed
     */
    public function findActiveBySlug($slug)
    {
        return $this->createQueryBuilder()
            ->field('slug')->equals($slug)
            ->field('user')->notEqual(null)
            ->field('is_active')->equals(true)
            ->getQuery()
            ->getSingleResult();
    }
}