<?php

namespace Gsup\ForumBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends DocumentRepository
{
    /**
     * Get list query.
     *
     * @return \Doctrine\MongoDB\Query\Query
     */
    public function getListQuery()
    {
        return $this->createQueryBuilder()
            ->field('user')->exists(true)
            ->field('is_active')->equals(true)
            ->sort('created_at', 'DESC')
            ->getQuery();
    }

    /**
     * Find active post document.
     *
     * @param $slug
     * @return mixed
     */
    public function findActiveBySlug($slug)
    {
        return $this->createQueryBuilder()
            ->field('slug')->equals($slug)
            ->field('user')->exists(true)
            ->field('is_active')->equals(true)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * @param $user
     * @return array|null|object
     */
    public function findAllInActiveByUser($user)
    {
        return $this->createQueryBuilder()
//            ->field('user.$id')->equals(new \MongoId($userId))
            ->field('user')->references($user)
            ->field('is_active')->equals(false)
            ->getQuery()
            ->execute();
    }
}