services:
    gsup_forum.login:
        class: Gsup\ForumBundle\EventListener\LoginPostAddListener
        arguments: [@fos_user.user_manager, @doctrine.odm.mongodb.document_manager]
        tags:
            - { name: kernel.event_subscriber }
#    gsup_forum.example:
#        class: Gsup\ForumBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
