Gsup\ForumBundle\Document\Post:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
        content:
            - NotBlank: { groups: [reply] }
        tags:
            - NotBlank: ~
        category:
            - NotBlank: ~

Gsup\ForumBundle\Document\Reply:
    properties:
        content:
            - NotBlank: { groups: [reply] }